$(document).ready(function(){
        $("#signup-form").validate({
            rules:{
            fname:{
                required:true,
                minlength:4

                  },
                  sname:{
                    required:true,
                    minlength:4
                  },
                  emailAddress:{
                  required:true,
                  email:true,
                  },
                  password:{
                    minlength:4
                  },
                  day:{
                    required:true,
                  }
         }
    })
})